server:
  port: 8090

spring:
  application:
    name: gateway-api11
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apiplatform?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    password:
    port: 6379
    database: 5
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# ?????
gateway:
  dynamicRoute:
    dataId: 'API_routes'
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-springboot-demo-provider
    enable-file-cahe: false
    #一次修改：添加
    qosEnable: true
    qosPort: 33333
    qosAcceptForeignIp: false
    #二次修改：添加
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848